receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: node-exporter
          scrape_interval: 10s

          static_configs:
            - targets: ['node-exporter:9100']

          metric_relabel_configs:
            - source_labels: [__name__]
              regex: 'node_memory_MemAvailable_bytes|node_memory_MemTotal_bytes|node_cpu_seconds_total|node_load1|node_load5|node_load15|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_disk_read_bytes_total|node_disk_written_bytes_total|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_network_receive_packets_total|node_network_transmit_packets_total|node_network_receive_errs_total|node_network_transmit_errs_total'
              action: keep

processors:
  resource:
    attributes:
      - key: repo
        value: "slma29/SMIS"
        action: upsert

      - key: token
        value: "${env:SENTINEL_TOKEN}"
        action: upsert

      - key: version
        value: "${env:REPO_VERSION}"
        action: upsert

      - key: correlation_id
        value: "slma29/SMIS|${env:REPO_VERSION}|${env:SENTINEL_TOKEN}"
        action: upsert

  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["repo"], resource.attributes["repo"])
          - set(attributes["token"], resource.attributes["token"])
          - set(attributes["version"], resource.attributes["version"])
          - set(attributes["correlation_id"], resource.attributes["correlation_id"])

  batch:
    timeout: 5s

exporters:
  otlphttp/metrics:
    endpoint: "https://societies-brave-beijing-larger.trycloudflare.com"
    encoding: json
    headers:
      X-Sentinel-Token: "${env:SENTINEL_TOKEN}"
      X-Sentinel-Secret: "${env:SENTINEL_SECRET}"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resource, transform, batch]
      exporters: [otlphttp/metrics]
