receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: node-exporter
          scrape_interval: 10s

          static_configs:
            - targets: ['node-exporter:9100']

          metric_relabel_configs:
            - source_labels: [__name__]
              regex: 'node_memory_MemAvailable_bytes|node_memory_MemTotal_bytes|node_cpu_seconds_total|node_load1|node_load5|node_load15|node_filesystem_avail_bytes|node_filesystem_size_bytes|node_disk_read_bytes_total|node_disk_written_bytes_total|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_network_receive_packets_total|node_network_transmit_packets_total|node_network_receive_errs_total|node_network_transmit_errs_total'
              action: keep

  filelog:
    include: [ "/var/lib/docker/containers/*/*.log" ]
    start_at: beginning

processors:
  resource:
    attributes:
      - key: repo
        value: "slma29/SMIS"
        action: upsert

      - key: token
        value: "${env:SENTINEL_TOKEN}"
        action: upsert

      - key: version
        value: "${env:REPO_VERSION}"
        action: upsert

      - key: correlation_id
        value: "slma29/SMIS|${env:REPO_VERSION}|${env:SENTINEL_TOKEN}"
        action: upsert

  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["signal_type"], "log")
          - set(attributes["source_category"], "filelog")

    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["repo"], resource.attributes["repo"])
          - set(attributes["token"], resource.attributes["token"])
          - set(attributes["version"], resource.attributes["version"])
          - set(attributes["correlation_id"], resource.attributes["correlation_id"])

  batch:
    timeout: 5s

exporters:
  otlphttp/logs:
    endpoint: "https://assess-tree-appeals-exhibits.trycloudflare.com"
    headers:
      X-Sentinel-Token: "${env:SENTINEL_TOKEN}"
      X-Sentinel-Secret: "${env:SENTINEL_SECRET}"

  otlphttp/metrics:
    endpoint: "https://assess-tree-appeals-exhibits.trycloudflare.com"
    headers:
      X-Sentinel-Token: "${env:SENTINEL_TOKEN}"
      X-Sentinel-Secret: "${env:SENTINEL_SECRET}"

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resource, transform, batch]
      exporters: [otlphttp/logs]

    metrics:
      receivers: [prometheus]
      processors: [resource, transform, batch]
      exporters: [otlphttp/metrics]
