version: '3.8'
services:
  sentinel-rasp:
    image: caeshoru/sentinel-rasp:latest
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    ports: ["8080:8081"]
    environment:
      - SENTINEL_SECRET=${SENTINEL_SECRET}
      - SENTINEL_TOKEN=${SENTINEL_TOKEN}
      - SENTINEL_URL=https://mas-food-sheets-inspector.trycloudflare.com/upload-intelligence
      - INTERNAL_APP_URL=http://app:8080
      - REPO_NAME=slma29/SMIS
      - REPO_VERSION=${REPO_VERSION:-unknown}

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      - node-exporter
      - sentinel-rasp
    tmpfs:
      - /tmp
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./otel-runtime-config.yaml:/etc/otel-config.yaml:ro
    command: ["--config=/etc/otel-config.yaml"]
